# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compartmental model function for a norovirus epidemic
#' @description A compartmental norovirus model with four age groups. This
#' function is intended to be passed to the \pkg{deSolve} function `lsoda`.
#' @param t Double value for the time.
#' @param state Vector of the initial state. The form of the vector should be
#' \eqn{X_i, for X \in S, E, I_s, I_a, R, I_new, I_re}, where values for each
#' of the compartments for each age group \eqn{i} are given consecutively.
#' @param parameters List for the parameters used in the simulation. See
#' [default_parameters()] for a list of parameters used in development.
#' @return A list with a single numeric vector of the same size as `state`,
#' suitable as output for [deSolve::lsoda()].
#' @export
norovirus_model_cpp <- function(t, state, parameters) {
    .Call(`_noromod_norovirus_model_cpp`, t, state, parameters)
}

#' @title Run an age-structured SEIRS for norovirus
#'
#' @param initial_conditions An integer matrix holding the initial conditions
#' of the simulation. Each column should represent one compartment, in the
#' order: susceptible, exposed, infectious and symptomatic, infectious and
#' asymptomatic, and recovered. Two extra columns for re-infections and
#' new infections are are required.
#' Rows must represent age groups.
#' @param params A `list` object with infection parameters.
#' @param time_end The maximum time, defaults to 200.0.
#' @param increment The increment time, defaults to 0.1.
#' @return A two element list, where the first element is a list of matrices
#' whose elements correspond to the numbers of individuals in each compartment
#' as specified in the initial conditions matrix.
#' The second list element is a vector of timesteps.
#' Pass this to the function `epidemics:::output_to_df()` to get a `data.table`
#' of simulation results.
#' @export
noromod_cpp_boost <- function(initial_conditions, params, time_end = 200.0, increment = 1.0) {
    .Call(`_noromod_noromod_cpp_boost`, initial_conditions, params, time_end, increment)
}

