# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Run an age-structured SEIRSV model for norovirus
#'
#' @param initial_conditions A numeric vector holding the initial conditions
#' of the simulation. Each column should represent one compartment, in the
#' order: susceptible, exposed, infectious and symptomatic, infectious and
#' asymptomatic, and recovered. Two extra columns for re-infections and
#' new infections are also required.
#' Further columns must represent the same compartments for each vaccination
#' stratum.
#' Rows must represent age groups.
#' @param params A `list` object with infection parameters; see the convenience
#' function [default_parameters()].
#' @param time_end The maximum time, defaults to 200.0.
#' @param increment The increment time, defaults to 1.0.
#' @return A two element list, where the first element is a list of matrices
#' whose elements correspond to the numbers of individuals in each compartment
#' as specified in the initial conditions matrix.
#' The second list element is a vector of timesteps.
#' @export
noromod_cpp_boost <- function(initial_conditions, params, time_end = 200.0, increment = 1.0) {
    .Call(`_noromod_noromod_cpp_boost`, initial_conditions, params, time_end, increment)
}

